from tkinter import *
top = Tk()
top.title("coffee machine")
L= Label(top, text = "THE COFFEE MACHINE",font=("Helvetica", 20, "bold"),fg="white",bg="black").place(x = 40, y = 0)
top.geometry("400x400")
L1= Label(top, text = "What would you like to have?",fg="black").place(x=0, y=40)
button_1 = Button(top, text = "ESPRESSO", fg = "cyan").place(x=80,y=70)
button_2 = Button(top, text = "LATTE", fg = "blue").place(x=150, y=70)
button_3 = Button(top, text = "CAPPUCCINO", fg = "magenta").place(x = 200, y = 70)
button_4 = Button(top, text = "OFF", fg = "purple").place(x = 290, y = 70)
n1 = StringVar()
n2 = StringVar()
n3 = StringVar()
n4 = StringVar()
L2= Label(top, text = "How many coins?",fg="#fc032d").place(x = 0, y = 110)
l1 = Label(top, text="How many quarters you want?").place(x=20, y=150)
l2 = Label(top, text="How many dimes you want?").place(x=20, y=200)
l3 = Label(top, text="How many nickles you want?").place(x=20, y=250)
l4 = Label(top, text="How many pennies you want?").place(x=20, y=300)
t1 = Entry(top, textvariable=n1).place(x=200, y=150)
t2 = Entry(top, textvariable=n2).place(x=200, y=200)
t3 = Entry(top, textvariable=n3).place(x=200, y=250)
t4 = Entry(top, textvariable=n4).place(x=200, y=300)
button_5 = Button(top, text = "ENTER", fg = "green").place(x = 190,y = 350)
top.mainloop()